--
-- create table Product;
-- create table Inventory;
-- create table Category;
--
-- insert into Category(`id`, `name`,`description`)
-- values(1, 'book', 'learningMaterial'),
--       (2, 'Ankara', 'clothingMaterial'),
--       (3, 'pot', 'cookingUtensil'),
--       (4, 'tomato', 'grocery')
--
-- insert into Product(`id`, `name,`price`)
-- values(1, 'book', 20.0),
--       (2, 'Ankara', 30.0),
--       (3, 'pot', 40.0),
--       (4, 'tomato', 50.0)
--
-- -- update table Category;
-- -- update table Product;